name: Java CI with Maven

on:
  push:
    branches: [ "branch-1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Appium Server
        run: |
          npm i --location=global appium
          appium driver install uiautomator2

      - name: Run Appium Server
        run: |
          appium &

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn test

